apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # cert-manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  # Envoy Gateway
  - https://github.com/envoyproxy/gateway/releases/download/v1.3.2/install.yaml
  # Gateway API (no need to add cause Envoy helps you add)
  # - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml
  # GatewayClass
  - gatewayclass.yaml
  # Gateway
  - gateway.yaml
  # KServe
  - https://github.com/kserve/kserve/releases/download/v0.15.0/kserve.yaml
  # KServe Runtimes
  - https://github.com/kserve/kserve/releases/download/v0.15.0/kserve-cluster-resources.yaml
patches:
  # Patch default deployment to RawDeployment and ingress to use gateway API
  - path: patchInferenceserviceConfig.yaml
