apiVersion: v1
kind: ConfigMap
metadata:
  name: the-map
data:
  deploy: |-
    {
      "defaultDeploymentMode": "RawDeployment"
    }
  ingress: |-
    {
      "enableGatewayApi": true,
      "kserveIngressGateway": "kserve/kserve-ingress-gateway",
    }
