apiVersion: v1
kind: Namespace
metadata:
  name:  "kserve-helloworld-infsvc"
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: "kserve-helloworld-infsvc"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
    deploymentStrategy:
      type: "RollingUpdate"
