apiVersion: v1
kind: Namespace
metadata:
  name: "kserve-triton"
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torchscript-cifar10
  namespace: kserve-triton
spec:
  predictor:
    triton:
      storageUri: gs://kfserving-examples/models/torchscript
      runtimeVersion: 25.03-py3
      env:
      - name: OMP_NUM_THREADS
        value: "1"
      protocolVersion: grpc-v2
      ports:
        - containerPort: 9000
          protocol: TCP
          name: grpc # MUST be grpc or h2c or h2c-port or similar for it to work
        
